# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 정현진
title: Software engineer
email: hyun0524e@naver.com
# email_title: Email (Email title override)
phone: 01028810909
# phone_title: Phone (Phone title override)
wiki: currenjin.github.io
wiki_title: Wiki
blog: simpleisit.tistory.com
blog_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  currenjin
instagram_username: currenjin
#twitter_username: jekyllrb
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: |
  Spring / NodeJS / Typescript / GraphQL / ReactJS / AWS 를 주로 사용해 온 개발자입니다. <mark>테스트</mark> 및 <mark>체크리스트</mark> 가 우선인 개발을 중요시하며, <mark>체크리스트 주도 개발(CDD)</mark> 이라는 개발 방법론을 만들어 팀 내에 공유했습니다.<br>
  도메인 프로젝트를 구현하고, 코드에 숨겨진 도메인을 드러내기 위한 설계 및 개선, 시스템 유지보수 등을 했습니다. 개인의 성장과 욕심보다는, 유저에게 전달되는 <mark>가치</mark> 가 가장 중요하다고 생각합니다. 항상 목적과 가치에 흥분합니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 트레바리(TREVARI)
        sub_title: 도메인 엔지니어(DE)
        caption: 2020.09 ~ 현재
        link: https://trevari.co.kr
        quote: >
          누적 회원 수 15 만 명과 함께한 프리미엄 독서모임 커뮤니티, 누적 90 억 투자 유치
        description: |
          - **신규 프로젝트 설계/개발/배포/운영**, 사용자스토리 기반/테스트 주도 개발을 통한 가치 전달.
          - **시스템 내 숨겨진 도메인을 드러냄**, 읽기 어려웠던 코드를 한 눈에 파악할 수 있도록 리팩토링 및 개선, 이해하기 위한 코드는 약 10,000 줄에서 15 줄로 감소.
          - AWS Lambda, EventBridge 를 통해 **하루 약 1,500 건의 문자 발송 자동화 및 유지보수**. Serverless framework 마이그레이션.
          - 운영 업무 자동화/효율화를 위한 **백오피스 기능 설계/개발/유지보수**, 크루의 관리 시간 약 70% 감소
      - layout: left
        title: 조인트리(JOINTREE)
        sub_title: 행정안전부 유지보수팀
        caption: 2019.02 ~ 2019.10
        quote: >
          내/외부망 합 3000대 규모 네트워크 관리 및 보안 업무 지원
        description: |
          - **Network 관리**
              L2/L3 Switch, Router, Backbone, IPT, 패킷분석, 통신회선 구축, 논리적/물리적 망분리, 원활한 통신 위한 효율성 고려 네트워크 구축
          - **보안업무 지원**
              통합관리시스템(EMS), 네트워크 차단/탐지 시스템(IPS/IDS), 네트워크 접근 통제 시스템(NAC), 방화벽(F/W), 사내 보안 정책
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Language
        description: |
          - Java, Javascript, Typescript
      - layout: left
        title: Backend
        description: |
          - Spring Boot, Spring MVC, Spring Batch, Spring Data JDBC, Spring Cloud AWS
          - NodeJS, GraphQL, Sequelize
          - Mockito, JUnit 4/5
          - Gradle
      - layout: left
        title: Frontend
        description: |
          - ReactJS, NextJS
          - NPM, Webpack
          - HTML, CSS
      - layout: left
        title: DevOps
        description: |
          - Postgresql, MySQL
          - Linux
          - Docker, Docker Compose, Dockerfile, Docker Image
          - AWS EC2, Elastic Beanstalk, SQS, SNS, SES, S3, RDS, Lambda, Cloud Watch, Event Bridge
      - layout: left
        title: Network
        description: |
          - Cisco Router/Switch configuration & installation
          - Alcatel L2/L3/Backbone configuration & installation
          - IP Phone Settings
          - Network Access Control

#  - title: Projects
#    layout: list
#    content:
#      - layout: left
#        border: weak
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: |
#          Description about the work on/with the project
  - title: Education
    layout: list
    content:
      - layout: left
        title: AWS 아키텍처 설계 및 운영 전문가 양성과정
        caption: 2019.12~ 2020.07
        quote: >
          AWS 클라우드 교육
        description: |
          - 클라우드를 향한 관심이 호감으로 바뀌어 수강한 교육
          - AWS Cloud, Openstack
          - 클라우드 뿐만 아니라 네트워크, 개발, 보안, 서버 분야 강의도 진행하며 전체적인 서비스 흐름을 파악
          - 본 과정 종합평가 <mark>최우수 교육생</mark>
      - layout: left
        title: 공주대학교 정보보호 영재교육원 수료
        caption: 2018.03 ~ 2018.11
        quote: >
          정보보호 분야에 관심을 보이는 이들을 선발 후 무상 정보보호 교육
        description: |
          - Spoofing, 사회공학공격 등의 해킹기법에 대해 대응방안 물색
          - 정보보호 기술 발표(블록체인 기술)
          - 사이버공격 대회
      - layout: left
        title: 국제기능올림픽대회 특별교육 이수
        caption: 2017.11
        quote: >
          한국산업인력공단 산하 Linux server 교육
        description: |
          - Bind9, Ldap, Apcahe 등의 서버 구축
          - Network service 구성
          - Directory, File System 관리
      - layout: left
        title: IT Network System
        caption: 2016.03 ~ 2019.02
        quote: >
          한국산업인력공단이 주최하는 기능경기대회를 목적으로 개설된 동아리
        description: |
          - Network/Server 이해와 구성 가능한 기술 수준을 요구
          - 2019 한국산업인력공단 <mark>표창</mark>
          - 2018 전국기능경기대회 <mark>장려상</mark>
          - 2018 대전지방기능경기대회 <mark>금메달</mark>
          - 2017 대전지방기능경기대회 <mark>은메달</mark>
          - 2016 (사)기능한국인회 <mark>장학생</mark>
      - layout: left
        title: 계룡디지텍고등학교 정보통신과
        caption: 2016.03 ~ 2019.02
        quote: >
          정보통신 특성화 고등학교
        description: |
          - 2019 <mark>기능상</mark>
          - 2018 교내 전공연구회 <mark>1위</mark>
          - 2017 교내 전공연구회 <mark>1위</mark>
  - title: Certificate
    layout: text
    content: |
      - 2020.07  Azure Certified AZ-900
      - 2020.02  Cisco Certificate Network Associate
      - 2019.05  정보처리산업기사
      - 2018.07  전기기능사
      - 2018.06  리눅스마스터 2급
      - 2016.09  네트워크관리사 2급
      - 2016.09  정보기기운용기능사
  - title: A Little More About Me
    layout: text
    content: |
      **도전을 즐긴다.**
      - 배는 항구에 있을 때 가장 안전합니다. 하지만 그것이 배가 존재하는 이유는 아닌 것처럼, 계속해서 항해하고 도전하는 '배'와 같은 사람입니다.

      **배움을 즐긴다.**
      - 사람의 지적 능력은 고정된 것이 아니라, 지속적으로 향상될 수 있다고 믿습니다. 배움에 대한 가치를 높게 평가하는 '자신'입니다.

      **꾸준함을 유지한다.**
      - 잘 알고 있는 도구라도 지속적으로 사용하지 않으면 무뎌지기 마련입니다. 빠르지 않더라도 멈추지 않는 꾸준함을 유지합니다.

      **얻은 것은 함께 나누자!**
      - 새롭게 터득하거나 배운 기술들을 여러 사람들과 함께 나누어 소통하며, 정보 공유의 중요성을 바탕으로 알고자 하는 사람들도 함께 배울 수 있도록 블로그 또는 개인 위키에 기록합니다.

      **이 외에도 저에 대해 더 궁금하다면 아래 링크를 확인해 주세요!**
      - [취미](https://www.notion.so/currenjin/My-Hobby-2c69332f072244079626b4221c818cd4)
      - [인터뷰](https://www.theteams.kr/teamterview/page/573)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
